// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {nameTID, commentTID, commentStartTID, expressionTID} from "./tokens"
import {indentation, trackIndent} from "../../nesting/indent"
export const parser = Parser.deserialize({
  version: 13,
  states: "&xQVQ!]OOOOQ!['#Ce'#CeOqQaO'#ChO!tQ!ZO'#CoOOQ!Y'#DR'#DRO#UQPO'#CgO#ZQuO'#CqO#iQuO'#CrOOQp'#Cp'#CpO#wQyO'#CfOOQ!['#Ct'#CtO$VQqO'#CtQVQ!]OOO$[QaO'#CiO$cQPO,59SOOQ`'#Ck'#CkOOQ`'#Cm'#CmOOQ`'#Cn'#CnOqQaO,59UOqQaO,59UOqQaO,59UOqQaO,59UOqQaO,59UOqQaO,59ROOQt'#Cu'#CuO$hQuO,59]O$vQuO,59^O%UQ!TO'#CsOOQ![,59Q,59QO%jQqO,59QOOQ![,59`,59`OOQ![-E6r-E6rOOQ!Y1G.n1G.nOOQ!Y1G.p1G.pO&jQ!ZO1G.pO&zQ!ZO1G.pO(YQ!ZO1G.pO(dQ!ZO1G.pO(nQ!ZO1G.mOOQt-E6s-E6sOOQ!S'#Cv'#CvO)OQ!TO,59_OOQ![1G.l1G.lOOQ!S-E6t-E6tOOQ![1G.y1G.y",
  stateData: ")V~OsOS~OPTORVOSSOTSOUSOmUOoPOvQO~OSSOTSOUSOvQO~OVfOnaOx_Oy`Oz`O{`O|aOS`PT`PU`Pv`P~ORcXmcXocXpcX~P!POtgO~OQhOlhOoeXpeX~OQhOlhOofXpfX~ORVOmUOolOpkO~OonO~Ow]X~P!POwpO~OQhOlhOoeapea~OQhOlhOofapfa~OPTOSSOTSOUSOoxOvQO~OozOpkO~Ox_OR^iV^im^in^io^ip^iy^iz^i{^i|^iw^i~OS^iT^iU^iv^i~P%rOS`PT`PU`Pv`P~P%rOx_Oy`Oz`O{`OR^iS`PT`PU`PV^im^io^ip^iv`Pw^i~On^i|^i~P'[OnaO|aO~P'[ORZimZioZipZi~P!POq|O~P%UO",
  goto: "$mvPPPPPPPPPw{!T!Z!h!Z!k!t!y#Q!T#W#_#_#d#j#p#zPPPPPPPPPP$QTYO[SYO[TxkyXXO[kygSOQ[bcdefgkyR^Q_bR]rstuvVcR]vZdR]tuvXeR]uvSZO[RmXVWOX[QlXRzmQ[ORo[QiUQjVTwijQykR{yWRO[kyQ]QQqbQrcQsdQteQufRvg",
  nodeNames: "⚠ Name URL NormalCommentStart Number Reference Unit BinOp Document BlankLine Statement Assignment Parens Expression BinaryExpression ArithOp ImplicitOp ArithOp ArithOp Expression Comment StrongComment NormalComment NestedStatements",
  maxTerm: 44,
  context: trackIndent,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "!v~RYXYqpqquv|xy!Ryz!Wz{!]{|!b!P!Q!g!_!`!l#Q#R!q~vQs~XYqpqq~!RO{~~!WOv~~!]Ow~~!bOy~~!gO|~~!lOz~~!qOt~~!vOx~",
  tokenizers: [0, nameTID, commentTID, commentStartTID, expressionTID, indentation],
  topRules: {"Document":[0,8]},
  tokenPrec: 0
})
