// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {nameTID, commentTID, commentStartTID, expressionTID} from "./tokens"
import {indentation, newlines, trackIndent} from "../../syntax/nesting/indent"
export const parser = Parser.deserialize({
  version: 13,
  states: "'UQVQ!}OOOOQ!|'#Ce'#CeOqQaO'#ChO!tQ#mO'#CnOOQ#l'#DQ'#DQO#UQPO'#CgO#ZQ#XO'#CpO#iQ#XO'#CqOOQ#S'#Co'#CoO#wQ#]O'#CfOOQ!|'#Cs'#CsO$VQ!cO'#CsQVQ!}OOO$[QaO,59SOOQ`'#Cj'#CjOOQ`'#Cl'#ClOOQ`'#Cm'#CmOqQaO,59TOqQaO,59TOqQaO,59TOqQaO,59TOqQaO,59TOqQaO,59ROOQ#W'#Ct'#CtO$cQ#XO,59[O$qQ#XO,59]O%PQ!uO'#CrOOQ#n,59Q,59QO%eQ!cO,59QO%jQ#TO,59QOOQ!|,59_,59_OOQ!|-E6q-E6qOOQ#l1G.n1G.nOOQ#l1G.o1G.oO&jQ#mO1G.oO&zQ#mO1G.oO(YQ#mO1G.oO(dQ#mO1G.oO(nQ#mO1G.mOOQ#W-E6r-E6rOOQ#f'#Cu'#CuO)OQ#gO,59^OOQ#n1G.l1G.lO)VQ!cO1G.lOOQ#f-E6s-E6sOOQ!b1G.x1G.xOOQ#n7+$W7+$W",
  stateData: ")[~OrOS~OPTORVOSSOTSOUSOlUOpPOuQO~OSSOTSOUSOuQO~OVeOm`Ow^Ox_Oy_Oz_O{`OS_PT_PU_Pu_P~ORbXlbXnbXpbX~P!POsfO~OQgOkgOpdXndX~OQgOkgOpeXneX~ORVOlUOnjOpkO~OpnO~OvpO~P!POQgOkgOpdanda~OQgOkgOpeanea~OPTOSSOTSOUSOpxOuQO~OpzO~OnjOpzO~Ow^OR]iV]il]im]in]ip]ix]iy]iz]i{]iv]i~OS]iT]iU]iu]i~P%rOS_PT_PU_Pu_P~P%rOw^Ox_Oy_Oz_OR]iS_PT_PU_PV]il]in]ip]iu_Pv]i~Om]i{]i~P'[Om`O{`O~P'[ORZilZinZipZi~P!POo}O~P%POp!OO~O",
  goto: "$iuPPPPPPPPPvz!S!Y!Y!g!p!u!|!S#S#Z#Z#`#f#l#vPPPPPPPPPP#|TYO[SYO[TxjyXXO[jygSOQ[abcdefjy_aR]rstuvVbR]vZcR]tuvXdR]uvSZO[RmXVWOX[QlXR{mQ[ORo[QhUQiVTwhiQyjR|yWRO[jyQ]QQqaQrbQscQtdQueRvf",
  nodeNames: "⚠ Name URL NormalCommentStart Number Reference Unit BinOp Document BlankLine Statement Assignment Parens BinaryExpression ArithOp ImplicitOp ArithOp ArithOp Expression Comment StrongComment NormalComment NestedStatements",
  maxTerm: 43,
  context: trackIndent,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "!v~RYXYqpqquv|xy!Ryz!Wz{!]{|!b!P!Q!g!_!`!l#Q#R!q~vQr~XYqpqq~!ROz~~!WOu~~!]Ov~~!bOx~~!gO{~~!lOy~~!qOs~~!vOw~",
  tokenizers: [0, nameTID, commentTID, commentStartTID, expressionTID, indentation, newlines],
  topRules: {"Document":[0,8]},
  tokenPrec: 0
})
