// Ignoring clashing currency symbol ¥ for currency cny in locale zh-CN
// Ignoring clashing currency symbol $ for currency twd in locale zh-TW
export const currencyUnits = {
  aed: { symbols: ["AED", "د.إ."] },
  afn: { symbols: ["AFN"] },
  all: { symbols: ["ALL"] },
  amd: { symbols: ["AMD"] },
  ang: { symbols: ["ANG"] },
  aoa: { symbols: ["AOA"] },
  ars: { symbols: ["ARS", "$AR"] },
  aud: { symbols: ["A$", "AU$", "AUD", "$AU"] },
  awg: { symbols: ["AWG"] },
  azn: { symbols: ["AZN"] },
  bam: { symbols: ["BAM"] },
  bbd: { symbols: ["BBD", "Bds$"] },
  bch: { symbols: ["BCH"] },
  bdt: { symbols: ["BDT"] },
  bgn: { symbols: ["BGN"] },
  bhd: { symbols: ["BHD", "د.ب."] },
  bif: { symbols: ["BIF"] },
  bmd: { symbols: ["BMD", "$BM", "BM$"] },
  bnd: { symbols: ["BND", "$BN"] },
  bob: { symbols: ["BOB"] },
  brl: { symbols: ["R$", "BRL", "BR$"] },
  bsd: { symbols: ["BSD", "BS$"] },
  btc: { symbols: ["BTC"] },
  btn: { symbols: ["BTN"] },
  bwp: { symbols: ["BWP"] },
  byr: { symbols: ["BYR"] },
  bzd: { symbols: ["BZD", "$BZ", "BZ$"] },
  cad: { symbols: ["CA$", "CAD", "$CA", "C$"] },
  cdf: { symbols: ["CDF"] },
  chf: { symbols: ["CHF"] },
  clf: { symbols: ["CLF"] },
  clp: { symbols: ["CLP", "$CL"] },
  cnh: { symbols: ["CNH"] },
  cny: { symbols: ["CN¥", "CNY", "元"] },
  cop: { symbols: ["COP", "$CO"] },
  crc: { symbols: ["CRC"] },
  cup: { symbols: ["CUP"] },
  cve: { symbols: ["CVE"] },
  czk: { symbols: ["CZK", "Kč"] },
  djf: { symbols: ["DJF"] },
  dkk: { symbols: ["DKK", "kr.", "Dkr"] },
  dop: { symbols: ["DOP", "RD$"] },
  dzd: { symbols: ["DZD", "د.ج."] },
  egp: { symbols: ["EGP", "ج.م.", "EG£"] },
  etb: { symbols: ["ETB"] },
  eth: { symbols: ["ETH"] },
  eur: { symbols: ["€", "EUR"] },
  fjd: { symbols: ["FJD", "$FJ", "FJ$"] },
  gbp: { symbols: ["£", "UK£", "GBP", "£GB"] },
  gel: { symbols: ["GEL"] },
  ghs: { symbols: ["GHS"] },
  gmd: { symbols: ["GMD"] },
  gnf: { symbols: ["GNF"] },
  gqe: { symbols: ["GQE"] },
  gtq: { symbols: ["GTQ"] },
  gyd: { symbols: ["GYD"] },
  hkd: { symbols: ["HK$", "HKD"] },
  hnl: { symbols: ["HNL"] },
  hrk: { symbols: ["HRK"] },
  htg: { symbols: ["HTG"] },
  huf: { symbols: ["HUF", "Ft"] },
  idr: { symbols: ["IDR", "Rp"] },
  ils: { symbols: ["₪", "ILS"] },
  inr: { symbols: ["₹", "INR", "Rs"] },
  iqd: { symbols: ["IQD", "د.ع."] },
  irr: { symbols: ["IRR", "ر.إ."] },
  isk: { symbols: ["ISK", "Ikr"] },
  jmd: { symbols: ["JMD", "JM$"] },
  jod: { symbols: ["JOD", "د.أ."] },
  jpy: { symbols: ["¥", "JP¥", "JPY", "￥"] },
  kes: { symbols: ["KES"] },
  kgs: { symbols: ["KGS"] },
  khr: { symbols: ["KHR"] },
  kmf: { symbols: ["KMF"] },
  kpw: { symbols: ["KPW"] },
  krw: { symbols: ["₩", "KRW", "￦"] },
  kwd: { symbols: ["KWD", "د.ك."] },
  kyd: { symbols: ["KYD"] },
  kzt: { symbols: ["KZT"] },
  lak: { symbols: ["LAK"] },
  lbp: { symbols: ["LBP", "ل.ل.", "£LB"] },
  lkr: { symbols: ["LKR"] },
  lrd: { symbols: ["LRD"] },
  lsl: { symbols: ["LSL"] },
  ltc: { symbols: ["LTC"] },
  lyd: { symbols: ["LYD", "د.ل."] },
  mad: { symbols: ["MAD", "د.م."] },
  mdl: { symbols: ["MDL"] },
  mga: { symbols: ["MGA"] },
  mkd: { symbols: ["MKD"] },
  mmk: { symbols: ["MMK"] },
  mnt: { symbols: ["MNT"] },
  mop: { symbols: ["MOP"] },
  mru: { symbols: ["MRU", "أ.م."] },
  mur: { symbols: ["MUR"] },
  mvr: { symbols: ["MVR"] },
  mwk: { symbols: ["MWK"] },
  mxn: { symbols: ["MX$", "MXN", "$MX"] },
  myr: { symbols: ["MYR"] },
  mzm: { symbols: ["MZM"] },
  mzn: { symbols: ["MZN"] },
  nad: { symbols: ["NAD", "$NA"] },
  ngn: { symbols: ["NGN"] },
  nio: { symbols: ["NIO"] },
  nok: { symbols: ["NOK", "Nkr"] },
  npr: { symbols: ["NPR"] },
  nzd: { symbols: ["NZ$", "NZD", "$NZ"] },
  omr: { symbols: ["OMR", "ر.ع."] },
  pab: { symbols: ["PAB"] },
  pen: { symbols: ["PEN"] },
  pgk: { symbols: ["PGK"] },
  php: { symbols: ["₱", "PHP"] },
  pkr: { symbols: ["PKR"] },
  pln: { symbols: ["PLN", "zł"] },
  pyg: { symbols: ["PYG"] },
  qar: { symbols: ["QAR", "ر.ق."] },
  ron: { symbols: ["RON"] },
  rsd: { symbols: ["RSD"] },
  rub: { symbols: ["RUB", "₽"] },
  rwf: { symbols: ["RWF"] },
  sar: { symbols: ["SAR", "ر.س."] },
  sbd: { symbols: ["SBD", "$SB", "SI$"] },
  scr: { symbols: ["SCR"] },
  sdg: { symbols: ["SDG", "ج.س."] },
  sek: { symbols: ["SEK", "kr"] },
  sgd: { symbols: ["SGD", "$SG"] },
  shp: { symbols: ["SHP"] },
  sll: { symbols: ["SLL"] },
  sos: { symbols: ["SOS"] },
  srd: { symbols: ["SRD", "$SR"] },
  svc: { symbols: ["SVC"] },
  syp: { symbols: ["SYP", "ل.س."] },
  szl: { symbols: ["SZL"] },
  thb: { symbols: ["THB", "฿"] },
  tjs: { symbols: ["TJS"] },
  tmt: { symbols: ["TMT", "ТМТ"] },
  tnd: { symbols: ["TND", "د.ت."] },
  top: { symbols: ["TOP"] },
  try: { symbols: ["TRY", "₺"] },
  ttd: { symbols: ["TTD", "$TT"] },
  twd: { symbols: ["NT$", "TWD"] },
  tzs: { symbols: ["TZS"] },
  uah: { symbols: ["UAH", "₴"] },
  ugx: { symbols: ["UGX"] },
  usd: { symbols: ["$", "US$", "$US", "USD"] },
  uyu: { symbols: ["UYU", "$UY"] },
  uzs: { symbols: ["UZS"] },
  vef: { symbols: ["VEF"] },
  vnd: { symbols: ["₫", "VND"] },
  vuv: { symbols: ["VUV"] },
  xaf: { symbols: ["FCFA", "XAF"] },
  xcd: { symbols: ["EC$", "XCD"] },
  xof: { symbols: ["F CFA", "XOF"] },
  xpf: { symbols: ["CFPF", "XPF", "FCFP"] },
  yer: { symbols: ["YER", "ر.ي."] },
  zar: { symbols: ["ZAR"] },
  zmw: { symbols: ["ZMW"] },
};
